const colors = {
  light: {
    text: '#0a0a0a',
    tint: '#7c3aed',
    background: '#f8f7ff',
    foreground: '#0a0a0a',
    card: '#ffffff',
    cardForeground: '#0a0a0a',
    primary: '#7c3aed',
    primaryForeground: '#ffffff',
    secondary: '#ede9fe',
    secondaryForeground: '#1a1a1a',
    muted: '#f3f4f6',
    mutedForeground: '#6b7280',
    accent: '#ede9fe',
    accentForeground: '#7c3aed',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#e5e7eb',
    input: '#e5e7eb',
    userBubble: '#7c3aed',
    userBubbleText: '#ffffff',
    aiBubble: '#f3f4f6',
    aiBubbleText: '#111827',
  },
  dark: {
    text: '#f0f0f0',
    tint: '#a78bfa',
    background: '#0d0d0f',
    foreground: '#f0f0f0',
    card: '#1a1a2e',
    cardForeground: '#f0f0f0',
    primary: '#8b5cf6',
    primaryForeground: '#ffffff',
    secondary: '#252542',
    secondaryForeground: '#f0f0f0',
    muted: '#1a1a2e',
    mutedForeground: '#9ca3af',
    accent: '#252542',
    accentForeground: '#a78bfa',
    destructive: '#ef4444',
    destructiveForeground: '#ffffff',
    border: '#2d2d4e',
    input: '#2d2d4e',
    userBubble: '#7c3aed',
    userBubbleText: '#ffffff',
    aiBubble: '#1a1a2e',
    aiBubbleText: '#f0f0f0',
  },
  radius: 16,
};

export default colors;
